package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"database/sql"
	"time"

	"github.com/uptrace/bun"
)

// Address represents a row from 'sakila.address'.
type Address struct {
	bun.BaseModel `bun:"table:address"`

	AddressID  uint16         `json:"address_id"`  // address_id
	Address    string         `json:"address"`     // address
	Address2   sql.NullString `json:"address2"`    // address2
	District   string         `json:"district"`    // district
	CityID     uint16         `json:"city_id"`     // city_id
	PostalCode sql.NullString `json:"postal_code"` // postal_code
	Phone      string         `json:"phone"`       // phone
	// // GEOMETRY型を[]byteとして扱う
	Location   []byte       `json:"location"`    // location
	LastUpdate time.Time      `json:"last_update"` // last_update
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the [Address] exists in the database.
func (a *Address) Exists() bool {
	return a._exists
}

// Deleted returns true when the [Address] has been marked for deletion
// from the database.
func (a *Address) Deleted() bool {
	return a._deleted
}

// Insert inserts the [Address] to the database.
func (a *Address) Insert(ctx context.Context, db DB) error {
	switch {
	case a._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case a._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (primary key generated and returned by database)
	const sqlstr = `INSERT INTO sakila.address (` +
		`address, address2, district, city_id, postal_code, phone, location, last_update` +
		`) VALUES (` +
		`?, ?, ?, ?, ?, ?, ?, ?` +
		`)`
	// run
	logf(sqlstr, a.Address, a.Address2, a.District, a.CityID, a.PostalCode, a.Phone, a.Location, a.LastUpdate)
	res, err := db.ExecContext(ctx, sqlstr, a.Address, a.Address2, a.District, a.CityID, a.PostalCode, a.Phone, a.Location, a.LastUpdate)
	if err != nil {
		return logerror(err)
	}
	// retrieve id
	id, err := res.LastInsertId()
	if err != nil {
		return logerror(err)
	} // set primary key
	a.AddressID = uint16(id)
	// set exists
	a._exists = true
	return nil
}

// Update updates a [Address] in the database.
func (a *Address) Update(ctx context.Context, db DB) error {
	switch {
	case !a._exists: // doesn't exist
		return logerror(&ErrUpdateFailed{ErrDoesNotExist})
	case a._deleted: // deleted
		return logerror(&ErrUpdateFailed{ErrMarkedForDeletion})
	}
	// update with primary key
	const sqlstr = `UPDATE sakila.address SET ` +
		`address = ?, address2 = ?, district = ?, city_id = ?, postal_code = ?, phone = ?, location = ?, last_update = ? ` +
		`WHERE address_id = ?`
	// run
	logf(sqlstr, a.Address, a.Address2, a.District, a.CityID, a.PostalCode, a.Phone, a.Location, a.LastUpdate, a.AddressID)
	if _, err := db.ExecContext(ctx, sqlstr, a.Address, a.Address2, a.District, a.CityID, a.PostalCode, a.Phone, a.Location, a.LastUpdate, a.AddressID); err != nil {
		return logerror(err)
	}
	return nil
}

// Save saves the [Address] to the database.
func (a *Address) Save(ctx context.Context, db DB) error {
	if a.Exists() {
		return a.Update(ctx, db)
	}
	return a.Insert(ctx, db)
}

// Upsert performs an upsert for [Address].
func (a *Address) Upsert(ctx context.Context, db DB) error {
	switch {
	case a._deleted: // deleted
		return logerror(&ErrUpsertFailed{ErrMarkedForDeletion})
	}
	// upsert
	const sqlstr = `INSERT INTO sakila.address (` +
		`address_id, address, address2, district, city_id, postal_code, phone, location, last_update` +
		`) VALUES (` +
		`?, ?, ?, ?, ?, ?, ?, ?, ?` +
		`)` +
		` ON DUPLICATE KEY UPDATE ` +
		`address = VALUES(address), address2 = VALUES(address2), district = VALUES(district), city_id = VALUES(city_id), postal_code = VALUES(postal_code), phone = VALUES(phone), location = VALUES(location), last_update = VALUES(last_update)`
	// run
	logf(sqlstr, a.AddressID, a.Address, a.Address2, a.District, a.CityID, a.PostalCode, a.Phone, a.Location, a.LastUpdate)
	if _, err := db.ExecContext(ctx, sqlstr, a.AddressID, a.Address, a.Address2, a.District, a.CityID, a.PostalCode, a.Phone, a.Location, a.LastUpdate); err != nil {
		return logerror(err)
	}
	// set exists
	a._exists = true
	return nil
}

// Delete deletes the [Address] from the database.
func (a *Address) Delete(ctx context.Context, db DB) error {
	switch {
	case !a._exists: // doesn't exist
		return nil
	case a._deleted: // deleted
		return nil
	}
	// delete with single primary key
	const sqlstr = `DELETE FROM sakila.address ` +
		`WHERE address_id = ?`
	// run
	logf(sqlstr, a.AddressID)
	if _, err := db.ExecContext(ctx, sqlstr, a.AddressID); err != nil {
		return logerror(err)
	}
	// set deleted
	a._deleted = true
	return nil
}

// AddressByAddressID retrieves a row from 'sakila.address' as a [Address].
//
// Generated from index 'address_address_id_pkey'.
func AddressByAddressID(ctx context.Context, db DB, addressID uint16) (*Address, error) {
	// query
	const sqlstr = `SELECT ` +
		`address_id, address, address2, district, city_id, postal_code, phone, location, last_update ` +
		`FROM sakila.address ` +
		`WHERE address_id = ?`
	// run
	logf(sqlstr, addressID)
	a := Address{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, addressID).Scan(&a.AddressID, &a.Address, &a.Address2, &a.District, &a.CityID, &a.PostalCode, &a.Phone, &a.Location, &a.LastUpdate); err != nil {
		return nil, logerror(err)
	}
	return &a, nil
}

// AddressByCityID retrieves a row from 'sakila.address' as a [Address].
//
// Generated from index 'idx_fk_city_id'.
func AddressByCityID(ctx context.Context, db DB, cityID uint16) ([]*Address, error) {
	// query
	const sqlstr = `SELECT ` +
		`address_id, address, address2, district, city_id, postal_code, phone, location, last_update ` +
		`FROM sakila.address ` +
		`WHERE city_id = ?`
	// run
	logf(sqlstr, cityID)
	rows, err := db.QueryContext(ctx, sqlstr, cityID)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()
	// process
	var res []*Address
	for rows.Next() {
		a := Address{
			_exists: true,
		}
		// scan
		if err := rows.Scan(&a.AddressID, &a.Address, &a.Address2, &a.District, &a.CityID, &a.PostalCode, &a.Phone, &a.Location, &a.LastUpdate); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &a)
	}
	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}

// AddressByLocation retrieves a row from 'sakila.address' as a [Address].
//
// Generated from index 'idx_location'.
func AddressByLocation(ctx context.Context, db DB, location []byte) ([]*Address, error) {
	// query
	const sqlstr = `SELECT ` +
		`address_id, address, address2, district, city_id, postal_code, phone, location, last_update ` +
		`FROM sakila.address ` +
		`WHERE location = ?`
	// run
	logf(sqlstr, location)
	rows, err := db.QueryContext(ctx, sqlstr, location)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()
	// process
	var res []*Address
	for rows.Next() {
		a := Address{
			_exists: true,
		}
		// scan
		if err := rows.Scan(&a.AddressID, &a.Address, &a.Address2, &a.District, &a.CityID, &a.PostalCode, &a.Phone, &a.Location, &a.LastUpdate); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &a)
	}
	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}

// City returns the City associated with the [Address]'s (CityID).
//
// Generated from foreign key 'fk_address_city'.
func (a *Address) City(ctx context.Context, db DB) (*City, error) {
	return CityByCityID(ctx, db, a.CityID)
}
