package models

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"

	"github.com/uptrace/bun"
)

// select `sakila`.`film`.`film_id` AS `FID`,`sakila`.`film`.`title` AS `title`,`sakila`.`film`.`description` AS `description`,`sakila`.`category`.`name` AS `category`,`sakila`.`film`.`rental_rate` AS `price`,`sakila`.`film`.`length` AS `length`,`sakila`.`film`.`rating` AS `rating`,group_concat(concat(`sakila`.`actor`.`first_name`,' ',`sakila`.`actor`.`last_name`) separator ', ') AS `actors` from ((((`sakila`.`film` left join `sakila`.`film_category` on((`sakila`.`film_category`.`film_id` = `sakila`.`film`.`film_id`))) left join `sakila`.`category` on((`sakila`.`category`.`category_id` = `sakila`.`film_category`.`category_id`))) left join `sakila`.`film_actor` on((`sakila`.`film`.`film_id` = `sakila`.`film_actor`.`film_id`))) left join `sakila`.`actor` on((`sakila`.`film_actor`.`actor_id` = `sakila`.`actor`.`actor_id`))) group by `sakila`.`film`.`film_id`,`sakila`.`category`.`name`
type FilmList struct {
	bun.BaseModel `bun:"table:film_list"`

	FID         uint16         `json:"FID"`         // FID
	Title       string         `json:"title"`       // title
	Description sql.NullString `json:"description"` // description
	Category    sql.NullString `json:"category"`    // category
	Price       float64        `json:"price"`       // price
	Length      sql.NullInt64  `json:"length"`      // length
	Rating      NullRating     `json:"rating"`      // rating
	Actors      sql.NullString `json:"actors"`      // actors
}
