package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// InventoryHeldByCustomer calls the stored function 'sakila.inventory_held_by_customer(int) int' on db.
func InventoryHeldByCustomer(ctx context.Context, db DB, pInventoryID int) (int, error) {
	// call sakila.inventory_held_by_customer
	const sqlstr = `SELECT sakila.inventory_held_by_customer(?)`
	// run
	var r0 int
	logf(sqlstr, pInventoryID)
	if err := db.QueryRowContext(ctx, sqlstr, pInventoryID).Scan(&r0); err != nil {
		return 0, logerror(err)
	}
	return r0, nil
}
