package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"fmt"
)

// FilmInStock calls the stored procedure 'sakila.film_in_stock(int, int) int' on db.
func FilmInStock(ctx context.Context, db DB, pFilmID, pStoreID int) (int, error) {
	// At the moment, the Go MySQL driver does not support stored procedures
	// with out parameters
	return 0, fmt.Errorf("unsupported")
}
