package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"fmt"
)

// RewardsReport calls the stored procedure 'sakila.rewards_report(tinyint, decimal) int' on db.
func RewardsReport(ctx context.Context, db DB, minMonthlyPurchases uint8, minDollarAmountPurchased float64) (int, error) {
	// At the moment, the Go MySQL driver does not support stored procedures
	// with out parameters
	return 0, fmt.Errorf("unsupported")
}
