package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

import (
	"context"
	"crypto/rand"
	"fmt"
	"log"
	"math/big"

	"github.com/ryo246912/playground-gqlgen/graph/model"
	"github.com/ryo246912/playground-gqlgen/graph/models"
)

// Store is the resolver for the store field.
func (r *customerResolver) Store(ctx context.Context, obj *model.Customer) (*model.Store, error) {
	var store models.Store

	err := r.DB.NewSelect().Model(&store).Where("store_id = ?", obj.StoreID).Scan(ctx)
	if err != nil {
		log.Print("error!", err)
		return nil, err
	}

	return &model.Store{
		ID:         fmt.Sprint(store.StoreID),
		LastUpdate: store.LastUpdate,
		AddressID:  fmt.Sprint(store.AddressID),
	}, nil
}

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	randNumber, _ := rand.Int(rand.Reader, big.NewInt(100))

	// todo := &model.Todo{
	// 	Text: input.Text,
	// 	ID:   fmt.Sprintf("T%d", randNumber),
	// 	User: &model.User{ID: input.UserID, Name: "user " + input.UserID},
	// }
	// NOTE:userIDをresolveする
	todo := &model.Todo{
		Text:   input.Text,
		ID:     fmt.Sprintf("T%d", randNumber),
		UserID: input.UserID,
	}

	r.todos = append(r.todos, todo)
	return todo, nil
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	return r.todos, nil
}

// Customers is the resolver for the customers field.
func (r *queryResolver) Customers(ctx context.Context) ([]*model.Customer, error) {
	var customers []models.Customer

	err := r.DB.NewSelect().Model(&customers).OrderExpr("customer_id ASC").Limit(10).Scan(ctx)
	if err != nil {
		log.Println("error!!", err)
		return nil, err
	}

	res := make([]*model.Customer, len(customers))
	for i, c := range customers {
		res[i] = &model.Customer{
			ID:         fmt.Sprint(c.CustomerID),
			FirstName:  c.FirstName,
			LastName:   c.LastName,
			Email:      *nullStringToPtr(c.Email),
			Active:     c.Active,
			CreateDate: c.CreateDate,
			LastUpdate: nullTimeToPtr(c.LastUpdate),
			StoreID:    fmt.Sprint(c.StoreID),
		}
	}

	return res, nil
}

// ManagerStaffs is the resolver for the managerStaffs field.
func (r *storeResolver) ManagerStaffs(ctx context.Context, obj *model.Store) ([]*model.Staff, error) {
	var staffs []models.Staff

	err := r.DB.NewSelect().Model(&staffs).Where("store_id = ?", obj.ID).Scan(ctx)
	if err != nil {
		log.Println("error!", err)
		return nil, err
	}

	res := make([]*model.Staff, len(staffs))
	for i, s := range staffs {
		res[i] = &model.Staff{
			FirstName:  s.FirstName,
			LastName:   s.LastName,
			Email:      nullStringToPtr(s.Email),
			Active:     s.Active,
			UserName:   s.Username,
			LastUpdate: s.LastUpdate,
		}
	}

	return res, nil
}

// Address is the resolver for the address field.
func (r *storeResolver) Address(ctx context.Context, obj *model.Store) (*model.Address, error) {
	var address models.Address

	err := r.DB.NewSelect().Model(&address).Where("address_id = ?", obj.AddressID).Scan(ctx)
	if err != nil {
		log.Println("error!", err)
		return nil, err
	}

	return &model.Address{
		ID:         fmt.Sprint(address.AddressID),
		Address:    address.Address,
		Address2:   nullStringToPtr(address.Address2),
		District:   stringToPtr(address.District),
		CityID:     int32(address.CityID),
		PostalCode: nullStringToPtr(address.PostalCode),
		LastUpdate: address.LastUpdate,
	}, nil
}

// User is the resolver for the user field.
// Note:resolver:trueにしたことで新たに生成された関数
func (r *todoResolver) User(ctx context.Context, obj *model.Todo) (*model.User, error) {
	return &model.User{ID: obj.UserID, Name: "user " + obj.UserID}, nil
}

// Customer returns CustomerResolver implementation.
func (r *Resolver) Customer() CustomerResolver { return &customerResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Store returns StoreResolver implementation.
func (r *Resolver) Store() StoreResolver { return &storeResolver{r} }

// Todo returns TodoResolver implementation.
func (r *Resolver) Todo() TodoResolver { return &todoResolver{r} }

type customerResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type storeResolver struct{ *Resolver }
type todoResolver struct{ *Resolver }
