// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Address struct {
	ID         string    `json:"ID"`
	Address    string    `json:"address"`
	Address2   *string   `json:"address2,omitempty"`
	District   *string   `json:"District,omitempty"`
	CityID     int32     `json:"CityID"`
	PostalCode *string   `json:"PostalCode,omitempty"`
	LastUpdate time.Time `json:"lastUpdate"`
}

type Mutation struct {
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Query struct {
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
