// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Customer struct {
	ID        string `json:"id"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Store     *Store `json:"store,omitempty"`
}

type Mutation struct {
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Query struct {
}

type Store struct {
	ID         string    `json:"id"`
	LastUpdate time.Time `json:"lastUpdate"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
