package db

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"

	"github.com/uptrace/bun"
)

// select `cu`.`customer_id` AS `ID`,concat(`cu`.`first_name`,' ',`cu`.`last_name`) AS `name`,`a`.`address` AS `address`,`a`.`postal_code` AS `zip code`,`a`.`phone` AS `phone`,`sakila`.`city`.`city` AS `city`,`sakila`.`country`.`country` AS `country`,if(`cu`.`active`,'active',”) AS `notes`,`cu`.`store_id` AS `SID` from (((`sakila`.`customer` `cu` join `sakila`.`address` `a` on((`cu`.`address_id` = `a`.`address_id`))) join `sakila`.`city` on((`a`.`city_id` = `sakila`.`city`.`city_id`))) join `sakila`.`country` on((`sakila`.`city`.`country_id` = `sakila`.`country`.`country_id`)))
type CustomerList struct {
	bun.BaseModel `bun:"table:customer_list"`

	ID      uint16         `json:"ID"`       // ID
	Name    sql.NullString `json:"name"`     // name
	Address string         `json:"address"`  // address
	ZipCode sql.NullString `json:"zip code"` // zip code
	Phone   string         `json:"phone"`    // phone
	City    string         `json:"city"`     // city
	Country string         `json:"country"`  // country
	Notes   string         `json:"notes"`    // notes
	SID     uint8          `json:"SID"`      // SID
}
