package db

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"database/sql"
	"time"

	"github.com/uptrace/bun"
)

// Payment represents a row from 'sakila.payment'.
type Payment struct {
	bun.BaseModel `bun:"table:payment"`

	PaymentID   uint16        `json:"payment_id"`   // payment_id
	CustomerID  uint16        `json:"customer_id"`  // customer_id
	StaffID     uint8         `json:"staff_id"`     // staff_id
	RentalID    sql.NullInt64 `json:"rental_id"`    // rental_id
	Amount      float64       `json:"amount"`       // amount
	PaymentDate time.Time     `json:"payment_date"` // payment_date
	LastUpdate  sql.NullTime  `json:"last_update"`  // last_update
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the [Payment] exists in the database.
func (p *Payment) Exists() bool {
	return p._exists
}

// Deleted returns true when the [Payment] has been marked for deletion
// from the database.
func (p *Payment) Deleted() bool {
	return p._deleted
}

// Insert inserts the [Payment] to the database.
func (p *Payment) Insert(ctx context.Context, db DB) error {
	switch {
	case p._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case p._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (primary key generated and returned by database)
	const sqlstr = `INSERT INTO sakila.payment (` +
		`customer_id, staff_id, rental_id, amount, payment_date, last_update` +
		`) VALUES (` +
		`?, ?, ?, ?, ?, ?` +
		`)`
	// run
	logf(sqlstr, p.CustomerID, p.StaffID, p.RentalID, p.Amount, p.PaymentDate, p.LastUpdate)
	res, err := db.ExecContext(ctx, sqlstr, p.CustomerID, p.StaffID, p.RentalID, p.Amount, p.PaymentDate, p.LastUpdate)
	if err != nil {
		return logerror(err)
	}
	// retrieve id
	id, err := res.LastInsertId()
	if err != nil {
		return logerror(err)
	} // set primary key
	p.PaymentID = uint16(id)
	// set exists
	p._exists = true
	return nil
}

// Update updates a [Payment] in the database.
func (p *Payment) Update(ctx context.Context, db DB) error {
	switch {
	case !p._exists: // doesn't exist
		return logerror(&ErrUpdateFailed{ErrDoesNotExist})
	case p._deleted: // deleted
		return logerror(&ErrUpdateFailed{ErrMarkedForDeletion})
	}
	// update with primary key
	const sqlstr = `UPDATE sakila.payment SET ` +
		`customer_id = ?, staff_id = ?, rental_id = ?, amount = ?, payment_date = ?, last_update = ? ` +
		`WHERE payment_id = ?`
	// run
	logf(sqlstr, p.CustomerID, p.StaffID, p.RentalID, p.Amount, p.PaymentDate, p.LastUpdate, p.PaymentID)
	if _, err := db.ExecContext(ctx, sqlstr, p.CustomerID, p.StaffID, p.RentalID, p.Amount, p.PaymentDate, p.LastUpdate, p.PaymentID); err != nil {
		return logerror(err)
	}
	return nil
}

// Save saves the [Payment] to the database.
func (p *Payment) Save(ctx context.Context, db DB) error {
	if p.Exists() {
		return p.Update(ctx, db)
	}
	return p.Insert(ctx, db)
}

// Upsert performs an upsert for [Payment].
func (p *Payment) Upsert(ctx context.Context, db DB) error {
	switch {
	case p._deleted: // deleted
		return logerror(&ErrUpsertFailed{ErrMarkedForDeletion})
	}
	// upsert
	const sqlstr = `INSERT INTO sakila.payment (` +
		`payment_id, customer_id, staff_id, rental_id, amount, payment_date, last_update` +
		`) VALUES (` +
		`?, ?, ?, ?, ?, ?, ?` +
		`)` +
		` ON DUPLICATE KEY UPDATE ` +
		`customer_id = VALUES(customer_id), staff_id = VALUES(staff_id), rental_id = VALUES(rental_id), amount = VALUES(amount), payment_date = VALUES(payment_date), last_update = VALUES(last_update)`
	// run
	logf(sqlstr, p.PaymentID, p.CustomerID, p.StaffID, p.RentalID, p.Amount, p.PaymentDate, p.LastUpdate)
	if _, err := db.ExecContext(ctx, sqlstr, p.PaymentID, p.CustomerID, p.StaffID, p.RentalID, p.Amount, p.PaymentDate, p.LastUpdate); err != nil {
		return logerror(err)
	}
	// set exists
	p._exists = true
	return nil
}

// Delete deletes the [Payment] from the database.
func (p *Payment) Delete(ctx context.Context, db DB) error {
	switch {
	case !p._exists: // doesn't exist
		return nil
	case p._deleted: // deleted
		return nil
	}
	// delete with single primary key
	const sqlstr = `DELETE FROM sakila.payment ` +
		`WHERE payment_id = ?`
	// run
	logf(sqlstr, p.PaymentID)
	if _, err := db.ExecContext(ctx, sqlstr, p.PaymentID); err != nil {
		return logerror(err)
	}
	// set deleted
	p._deleted = true
	return nil
}

// PaymentByRentalID retrieves a row from 'sakila.payment' as a [Payment].
//
// Generated from index 'fk_payment_rental'.
func PaymentByRentalID(ctx context.Context, db DB, rentalID sql.NullInt64) ([]*Payment, error) {
	// query
	const sqlstr = `SELECT ` +
		`payment_id, customer_id, staff_id, rental_id, amount, payment_date, last_update ` +
		`FROM sakila.payment ` +
		`WHERE rental_id = ?`
	// run
	logf(sqlstr, rentalID)
	rows, err := db.QueryContext(ctx, sqlstr, rentalID)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()
	// process
	var res []*Payment
	for rows.Next() {
		p := Payment{
			_exists: true,
		}
		// scan
		if err := rows.Scan(&p.PaymentID, &p.CustomerID, &p.StaffID, &p.RentalID, &p.Amount, &p.PaymentDate, &p.LastUpdate); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &p)
	}
	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}

// PaymentByCustomerID retrieves a row from 'sakila.payment' as a [Payment].
//
// Generated from index 'idx_fk_customer_id'.
func PaymentByCustomerID(ctx context.Context, db DB, customerID uint16) ([]*Payment, error) {
	// query
	const sqlstr = `SELECT ` +
		`payment_id, customer_id, staff_id, rental_id, amount, payment_date, last_update ` +
		`FROM sakila.payment ` +
		`WHERE customer_id = ?`
	// run
	logf(sqlstr, customerID)
	rows, err := db.QueryContext(ctx, sqlstr, customerID)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()
	// process
	var res []*Payment
	for rows.Next() {
		p := Payment{
			_exists: true,
		}
		// scan
		if err := rows.Scan(&p.PaymentID, &p.CustomerID, &p.StaffID, &p.RentalID, &p.Amount, &p.PaymentDate, &p.LastUpdate); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &p)
	}
	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}

// PaymentByStaffID retrieves a row from 'sakila.payment' as a [Payment].
//
// Generated from index 'idx_fk_staff_id'.
func PaymentByStaffID(ctx context.Context, db DB, staffID uint8) ([]*Payment, error) {
	// query
	const sqlstr = `SELECT ` +
		`payment_id, customer_id, staff_id, rental_id, amount, payment_date, last_update ` +
		`FROM sakila.payment ` +
		`WHERE staff_id = ?`
	// run
	logf(sqlstr, staffID)
	rows, err := db.QueryContext(ctx, sqlstr, staffID)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()
	// process
	var res []*Payment
	for rows.Next() {
		p := Payment{
			_exists: true,
		}
		// scan
		if err := rows.Scan(&p.PaymentID, &p.CustomerID, &p.StaffID, &p.RentalID, &p.Amount, &p.PaymentDate, &p.LastUpdate); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &p)
	}
	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}

// PaymentByPaymentID retrieves a row from 'sakila.payment' as a [Payment].
//
// Generated from index 'payment_payment_id_pkey'.
func PaymentByPaymentID(ctx context.Context, db DB, paymentID uint16) (*Payment, error) {
	// query
	const sqlstr = `SELECT ` +
		`payment_id, customer_id, staff_id, rental_id, amount, payment_date, last_update ` +
		`FROM sakila.payment ` +
		`WHERE payment_id = ?`
	// run
	logf(sqlstr, paymentID)
	p := Payment{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, paymentID).Scan(&p.PaymentID, &p.CustomerID, &p.StaffID, &p.RentalID, &p.Amount, &p.PaymentDate, &p.LastUpdate); err != nil {
		return nil, logerror(err)
	}
	return &p, nil
}

// Customer returns the Customer associated with the [Payment]'s (CustomerID).
//
// Generated from foreign key 'fk_payment_customer'.
func (p *Payment) Customer(ctx context.Context, db DB) (*Customer, error) {
	return CustomerByCustomerID(ctx, db, p.CustomerID)
}

// Rental returns the Rental associated with the [Payment]'s (RentalID).
//
// Generated from foreign key 'fk_payment_rental'.
func (p *Payment) Rental(ctx context.Context, db DB) (*Rental, error) {
	return RentalByRentalID(ctx, db, int(p.RentalID.Int64))
}

// Staff returns the Staff associated with the [Payment]'s (StaffID).
//
// Generated from foreign key 'fk_payment_staff'.
func (p *Payment) Staff(ctx context.Context, db DB) (*Staff, error) {
	return StaffByStaffID(ctx, db, p.StaffID)
}
