package db

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"time"
)

// GetCustomerBalance calls the stored function 'sakila.get_customer_balance(int, datetime) decimal' on db.
func GetCustomerBalance(ctx context.Context, db DB, pCustomerID int, pEffectiveDate time.Time) (float64, error) {
	// call sakila.get_customer_balance
	const sqlstr = `SELECT sakila.get_customer_balance(?, ?)`
	// run
	var r0 float64
	logf(sqlstr, pCustomerID, pEffectiveDate)
	if err := db.QueryRowContext(ctx, sqlstr, pCustomerID, pEffectiveDate).Scan(&r0); err != nil {
		return 0.0, logerror(err)
	}
	return r0, nil
}
