package db

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"

	"github.com/uptrace/bun"
)

// select `s`.`staff_id` AS `ID`,concat(`s`.`first_name`,' ',`s`.`last_name`) AS `name`,`a`.`address` AS `address`,`a`.`postal_code` AS `zip code`,`a`.`phone` AS `phone`,`sakila`.`city`.`city` AS `city`,`sakila`.`country`.`country` AS `country`,`s`.`store_id` AS `SID` from (((`sakila`.`staff` `s` join `sakila`.`address` `a` on((`s`.`address_id` = `a`.`address_id`))) join `sakila`.`city` on((`a`.`city_id` = `sakila`.`city`.`city_id`))) join `sakila`.`country` on((`sakila`.`city`.`country_id` = `sakila`.`country`.`country_id`)))
type StaffList struct {
	bun.BaseModel `bun:"table:staff_list"`

	ID      uint8          `json:"ID"`       // ID
	Name    sql.NullString `json:"name"`     // name
	Address string         `json:"address"`  // address
	ZipCode sql.NullString `json:"zip code"` // zip code
	Phone   string         `json:"phone"`    // phone
	City    string         `json:"city"`     // city
	Country string         `json:"country"`  // country
	SID     uint8          `json:"SID"`      // SID
}
